### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by TheLazyCodernothacker** [actiniumn404/Hackathon-Notes#1]
You set .innerHTML in signup page, you will get XSS attacked :0

**Comment by actiniumn404** [comment]
I don't really think this is a big deal, since the relevant code block is:

```js
let URL = new URLSearchParams(location.search)

if (URL.has("err")){
    let err = document.createElement("DIV")
    err.id = "error"
    err.innerHTML = "<b>Error: </b>" + decodeURIComponent(URL.get("err"))
    document.getElementById("wrapper").prepend(err)
}
```

In other words, the innerHTML is used in accordance with the URL. Therefore, for someone to exploit this, they would have to embed the HTML code in the URL and convince the user to click it. By that point, the attacker would probably be better off just sending the user to a malicious site.
